# Generated by Django 5.0.7 on 2024-10-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=60, unique=True)),
                ('initial_quantity', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('safety_stock', models.IntegerField()),
                ('lead_time_days', models.IntegerField()),
                ('demand_rate', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holding_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordering_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
