# Generated by Django 5.0.7 on 2024-10-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='safety_stock',
        ),
    ]
